items/urls.py
from django.urls import path

from . import views

app_name = 'items'

urlpatterns = [
    path('', views.myitem, name='myitem'),
]

kedaipedia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('myitem/', include('items.urls')),
    path('wishlist/', include('wishlist.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.daftarharapan, name='daftarharapan'),
]

items/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    nama_item = models.CharField(max_length=50)
    tipe_item = [
        ('ELT', 'Elektronik'),
        ('FNB', 'Food And Beverages'),
        ('CLO', 'Pakaian'),
        ('HEA', 'Produk Kesehatan atau Kecantikan'),
        ('KIT', 'Peralatan Dapur'),
        ('OFF', 'Peralatan kantor'),
        ('OTH', 'Lainnya')
    ]
    harga_item = models.IntegerField()
    deskripsi_item = models.TextField()

main/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class Harapan (models.Model):
    namaproduk = models.CharField(max_length=100)
    hargaproduk= models.CharField(max_length=100)

    def __str__(self):
        return self.namaproduk

wishlist/forms.py
from django import forms
from .models import Harapan

class HarapanForms(forms.ModelForm):
    namaproduk=forms.CharField(label='')
    namaproduk.widget.attrs.update({'class':'wishlist-form', 'required':'required'})
    hargaproduk= forms.CharField(label='')
    hargaproduk.widget.attrs.update({'class':'wishlist-form', 'required':'required'})

    class Meta:
        model = Harapan
        fields = ['namaproduk','hargaproduk']

items/views.py
from django.shortcuts import render

# Create your views here.

def myitem(request):
    return render(request, 'items/myitem.html')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

wishlist/views.py
from django.shortcuts import render
from .models import Harapan
from .forms import HarapanForms

# Create your views here.

def daftarharapan(request):
    data = Harapan.objects.all() 
    form = HarapanForms()
    if request.method == "POST":  
        form = HarapanForms(request.POST)  
        if form.is_valid():
            try:  
                form.save()   
            except:  
                pass  
    else:  
        form = HarapanForms()

    response = {
        'form': form,
        'data' : data,
        
    }  
    return render(request, 'wishlist/daftarharapan.html')

items/templates/items/myitem.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %}

    

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %}

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>kedaipedia</title>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <!-- Just an image -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{% static 'img/kedaipedia.png' %}" width="80"alt="" style="margin-left: 50px;">
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="margin-left: 20px;">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="#">Home</a>
      <a class="nav-item nav-link" href="{% url 'items:myitem' %}">Items</a>
      <a class="nav-item nav-link" href="{% url 'wishlist:daftarharapan' %}">Wishlist</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>
  {% block content %}

  {% endblock content %}
</body>

</html>

wishlist/templates/wishlist/daftarharapan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %}
<body>
    <div class="container">
        <h1> WishList </h1>
        <form method="POST" class="post-form" action="">
            {% csrf_token %}
            <label for="ProductName">Nama Produk:</label><br>
            <input type="text">{{form.namaproduk}}<br>
            <label for="Price">Perkiraan Harga</label><br>
            <input type="text" >{{form.hargaproduk}}<br><br>
            <input type="submit" value="Submit">
          </form> 
    </div>
    


    <h2>Daftar Kebutuhan:</h2>
        <table id="Produk">
        <tr>
          <th>Nama Produk</th>
          <th>Perkiraan Harga</th>
        </tr>
        {% for i in wishlist %}
        <tr>
            <td>{{i.namaproduk}}</td>
            <td>{{i.hargaproduk}}</td>
        </tr>
        </table>
        {% endfor %}
</body>
    

{% endblock content %}